import type { Metadata } from "next";
import "./globals.css";
import { AppInit } from "./init/AppInit";
import Script from "next/script";

export const metadata: Metadata = {
  title: "mybeans",
  description: "Generated by mybeans",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <AppInit />
        <div className="min-w-[768px] overflow-x-auto">{children}</div>

        <Script
          src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
